apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-management
  labels:
    app: loan-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-management
  template:
    metadata:
      labels:
        app: loan-management
    spec:
      containers:
        - name: loan-management
          image: 329599629502.dkr.ecr.eu-west-3.amazonaws.com/loan-management:6
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_APPLICATION_NAME
              value: "Loan_Management"
            - name: SERVER_PORT
              value: "8087"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://database-1.c9smueeigd2l.eu-west-3.rds.amazonaws.com/loan_management"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""  # Remplacez par votre mot de passe
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQL8Dialect"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: "INFO"
            - name: LOGGING_LEVEL_COM_PROJECT_LOAN_MANAGEMENT
              value: "DEBUG"
            - name: TRANSACTION_API_URL
              value: http://transactions-service:8084/payment/loan
            - name: PREDICTION_API_URL
              value: http://loan-management-service:5000/predict_api
      imagePullSecrets:
        - name: your-docker-registry-secret  # Si vous utilisez un registre privé